import type { PersonalityTemplate } from '../types'

export const PERSONALITY_TEMPLATES: Record<string, PersonalityTemplate> = {
  curious_beginner: {
    id: 'curious_beginner',
    label: 'Curious Beginner',
    personalityMode: 'supportive',
    immersionLevel: 'beginner',
    traits: {
      mistakeRate: 0.35,
      topicSwitchRate: 0.15,
      shortReplyBias: 0.25,
      unpredictability: 0.3,
      emotionalReactivity: 0.5,
      patience: 0.7,
    },
    defaultGoal: 'learn_vocab',
    emotionBias: 'curious',
  },
  playful_n4: {
    id: 'playful_n4',
    label: 'Playful N4',
    personalityMode: 'playful',
    immersionLevel: 'intermediate',
    traits: {
      mistakeRate: 0.2,
      topicSwitchRate: 0.35,
      shortReplyBias: 0.4,
      unpredictability: 0.55,
      emotionalReactivity: 0.65,
      patience: 0.5,
    },
    defaultGoal: 'small_talk',
    emotionBias: 'excited',
  },
  strict_student: {
    id: 'strict_student',
    label: 'Strict Student',
    personalityMode: 'teacher',
    immersionLevel: 'intermediate',
    traits: {
      mistakeRate: 0.1,
      topicSwitchRate: 0.08,
      shortReplyBias: 0.15,
      unpredictability: 0.15,
      emotionalReactivity: 0.35,
      patience: 0.85,
    },
    defaultGoal: 'practice_grammar',
    emotionBias: 'neutral',
  },
  shy_speaker: {
    id: 'shy_speaker',
    label: 'Shy Speaker',
    personalityMode: 'calm',
    immersionLevel: 'beginner',
    traits: {
      mistakeRate: 0.25,
      topicSwitchRate: 0.1,
      shortReplyBias: 0.7,
      unpredictability: 0.25,
      emotionalReactivity: 0.4,
      patience: 0.6,
    },
    defaultGoal: 'small_talk',
    emotionBias: 'shy',
  },
  bored_commuter: {
    id: 'bored_commuter',
    label: 'Bored Commuter',
    personalityMode: 'casual_friend',
    immersionLevel: 'beginner',
    traits: {
      mistakeRate: 0.15,
      topicSwitchRate: 0.45,
      shortReplyBias: 0.65,
      unpredictability: 0.5,
      emotionalReactivity: 0.3,
      patience: 0.25,
    },
    defaultGoal: 'free_chat',
    emotionBias: 'bored',
  },
  confused_learner: {
    id: 'confused_learner',
    label: 'Confused Learner',
    personalityMode: 'strict_tutor',
    immersionLevel: 'beginner',
    traits: {
      mistakeRate: 0.4,
      topicSwitchRate: 0.12,
      shortReplyBias: 0.35,
      unpredictability: 0.4,
      emotionalReactivity: 0.7,
      patience: 0.4,
    },
    defaultGoal: 'get_help',
    emotionBias: 'confused',
  },
  scenario_traveler: {
    id: 'scenario_traveler',
    label: 'Scenario Traveler',
    personalityMode: 'casual_friend',
    immersionLevel: 'intermediate',
    traits: {
      mistakeRate: 0.18,
      topicSwitchRate: 0.2,
      shortReplyBias: 0.3,
      unpredictability: 0.35,
      emotionalReactivity: 0.55,
      patience: 0.65,
    },
    defaultGoal: 'scenario_roleplay',
    emotionBias: 'curious',
  },
  advanced_chatter: {
    id: 'advanced_chatter',
    label: 'Advanced Chatter',
    personalityMode: 'philosophical',
    immersionLevel: 'advanced',
    traits: {
      mistakeRate: 0.08,
      topicSwitchRate: 0.28,
      shortReplyBias: 0.2,
      unpredictability: 0.45,
      emotionalReactivity: 0.5,
      patience: 0.75,
    },
    defaultGoal: 'free_chat',
    emotionBias: 'neutral',
  },
}

export const ALL_PERSONALITY_IDS = Object.keys(PERSONALITY_TEMPLATES)
