import type {
  PersonalityLine,
  Sentence,
  Suggestion,
  VocabEntry,
} from '@/types/domain'
import { withGrammarTags } from '@/utils/grammarTagInference'

const RAW_SEED_SENTENCES: Sentence[] = [
  {
    id: 1,
    jp: '今日はどうだった？',
    romaji: 'Kyou wa dou datta?',
    en: 'How was your day?',
    category: 'daily',
    jlptLevel: 'N5',
  },
  {
    id: 2,
    jp: 'そっか、大変だったね。',
    romaji: 'Sokka, taihen datta ne.',
    en: 'I see, that must have been tough.',
    category: 'daily',
    jlptLevel: 'N5',
  },
  {
    id: 3,
    jp: 'お疲れさま。',
    romaji: 'Otsukaresama.',
    en: 'Good work today.',
    category: 'daily',
    jlptLevel: 'N5',
  },
  {
    id: 4,
    jp: 'うん、疲れた。',
    romaji: 'Un, tsukareta.',
    en: "Yeah, I'm tired.",
    category: 'daily',
    jlptLevel: 'N5',
  },
  {
    id: 5,
    jp: 'でも楽しかった。',
    romaji: 'Demo tanoshikatta.',
    en: 'But it was fun.',
    category: 'daily',
    jlptLevel: 'N5',
  },
  {
    id: 6,
    jp: '今日は忙しかった。',
    romaji: 'Kyou wa isogashikatta.',
    en: 'Today was busy.',
    category: 'daily',
    jlptLevel: 'N5',
  },
  {
    id: 7,
    jp: '何があったの？',
    romaji: 'Nani ga atta no?',
    en: 'What happened?',
    category: 'daily',
    jlptLevel: 'N5',
  },
  {
    id: 8,
    jp: 'こんにちは！',
    romaji: 'Konnichiwa!',
    en: 'Hello!',
    category: 'greeting',
    jlptLevel: 'N5',
  },
  {
    id: 9,
    jp: '元気？',
    romaji: 'Genki?',
    en: 'How are you?',
    category: 'greeting',
    jlptLevel: 'N5',
  },
  {
    id: 10,
    jp: 'また話そうね。',
    romaji: 'Mata hanasou ne.',
    en: "Let's talk again.",
    category: 'daily',
    jlptLevel: 'N5',
  },
  {
    id: 11,
    jp: 'それは大変だったね。もっと聞かせて。',
    romaji: 'Sore wa taihen datta ne. Motto kikasete.',
    en: 'That sounds tough. Tell me more.',
    category: 'daily',
    jlptLevel: 'N5',
  },
  {
    id: 12,
    jp: 'いいね！他には？',
    romaji: 'Ii ne! Hoka ni wa?',
    en: 'Nice! What else?',
    category: 'daily',
    jlptLevel: 'N5',
  },
  {
    id: 13,
    jp: 'なるほど。それから？',
    romaji: 'Naruhodo. Sore kara?',
    en: 'I see. And then?',
    category: 'daily',
    jlptLevel: 'N5',
  },
  {
    id: 14,
    jp: '週末は何をする予定？',
    romaji: 'Shuumatsu wa nani wo suru yotei?',
    en: 'Any plans for the weekend?',
    category: 'daily',
    jlptLevel: 'N5',
  },
  {
    id: 15,
    jp: '最近ハマってることある？',
    romaji: 'Saikin hamatteru koto aru?',
    en: 'Anything you are into lately?',
    category: 'hobby',
    jlptLevel: 'N5',
  },
  {
    id: 16,
    jp: '日本語、よく頑張ってるね。',
    romaji: 'Nihongo, yoku ganbatteru ne.',
    en: 'You are working hard at Japanese.',
    category: 'study',
    jlptLevel: 'N5',
  },
  {
    id: 17,
    jp: 'ゆっくり説明するね。',
    romaji: 'Yukkuri setsumei suru ne.',
    en: 'Let me explain slowly.',
    category: 'study',
    jlptLevel: 'N5',
  },
  // ─── Scenario intents (train_station, hotel, dating, classroom) ───
  {
    id: 1001,
    jp: 'この電車は新宿行きですか？',
    romaji: 'Kono densha wa Shinjuku yuki desu ka?',
    en: 'Is this train bound for Shinjuku?',
    category: 'train_station',
    jlptLevel: 'N5',
  },
  {
    id: 1002,
    jp: '切符を二枚ください。',
    romaji: 'Kippu wo nimai kudasai.',
    en: 'Two tickets, please.',
    category: 'train_station',
    jlptLevel: 'N5',
  },
  {
    id: 1003,
    jp: 'ホームはどこですか？',
    romaji: 'Hoomu wa doko desu ka?',
    en: 'Which platform is it?',
    category: 'train_station',
    jlptLevel: 'N5',
  },
  {
    id: 1004,
    jp: '乗り換えはどこですか？',
    romaji: 'Norikae wa doko desu ka?',
    en: 'Where do I transfer?',
    category: 'train_station',
    jlptLevel: 'N5',
  },
  {
    id: 1005,
    jp: '少し遅れていますね。',
    romaji: 'Sukoshi okurete imasu ne.',
    en: "It's running a bit late.",
    category: 'train_station',
    jlptLevel: 'N5',
  },
  {
    id: 1006,
    jp: '座れますか？',
    romaji: 'Suwaremasu ka?',
    en: 'Can I sit here?',
    category: 'train_station',
    jlptLevel: 'N5',
  },
  {
    id: 1007,
    jp: 'チェックインをお願いします。',
    romaji: 'Chekkuin wo onegaishimasu.',
    en: "I'd like to check in, please.",
    category: 'hotel',
    jlptLevel: 'N5',
  },
  {
    id: 1008,
    jp: '部屋は禁煙ですか？',
    romaji: 'Heya wa kinen desu ka?',
    en: 'Is the room non-smoking?',
    category: 'hotel',
    jlptLevel: 'N5',
  },
  {
    id: 1009,
    jp: 'Wi-Fiのパスワードは何ですか？',
    romaji: 'Waifai no pasuwaado wa nan desu ka?',
    en: "What's the Wi-Fi password?",
    category: 'hotel',
    jlptLevel: 'N5',
  },
  {
    id: 1010,
    jp: '朝食は何時からですか？',
    romaji: 'Choushoku wa nanji kara desu ka?',
    en: 'What time is breakfast from?',
    category: 'hotel',
    jlptLevel: 'N5',
  },
  {
    id: 1011,
    jp: '荷物を預けられますか？',
    romaji: 'Nimotsu wo azukeraremasu ka?',
    en: 'Can I leave my luggage here?',
    category: 'hotel',
    jlptLevel: 'N5',
  },
  {
    id: 1012,
    jp: 'お部屋の鍵をなくしました。',
    romaji: 'Oheya no kagi wo nakushimashita.',
    en: 'I lost my room key.',
    category: 'hotel',
    jlptLevel: 'N5',
  },
  {
    id: 1013,
    jp: '久しぶり！元気だった？',
    romaji: 'Hisashiburi! Genki datta?',
    en: 'Long time no see! How have you been?',
    category: 'dating',
    jlptLevel: 'N5',
  },
  {
    id: 1014,
    jp: '今日は楽しかったね。',
    romaji: 'Kyou wa tanoshikatta ne.',
    en: 'Today was fun.',
    category: 'dating',
    jlptLevel: 'N5',
  },
  {
    id: 1015,
    jp: 'また会いたいな。',
    romaji: 'Mata aitai na.',
    en: 'I want to see you again.',
    category: 'dating',
    jlptLevel: 'N5',
  },
  {
    id: 1016,
    jp: '好きな映画は何？',
    romaji: 'Suki na eiga wa nani?',
    en: 'What movies do you like?',
    category: 'dating',
    jlptLevel: 'N5',
  },
  {
    id: 1017,
    jp: '次はどこに行きたい？',
    romaji: 'Tsugi wa doko ni ikitai?',
    en: 'Where do you want to go next?',
    category: 'dating',
    jlptLevel: 'N5',
  },
  {
    id: 1018,
    jp: '今日の授業は難しかった。',
    romaji: 'Kyou no jugyou wa muzukashikatta.',
    en: "Today's class was difficult.",
    category: 'classroom',
    jlptLevel: 'N5',
  },
  {
    id: 1019,
    jp: '宿題は終わった？',
    romaji: 'Shukudai wa owatta?',
    en: 'Did you finish the homework?',
    category: 'classroom',
    jlptLevel: 'N5',
  },
  {
    id: 1020,
    jp: '先生は優しいですね。',
    romaji: 'Sensei wa yasashii desu ne.',
    en: 'The teacher is kind.',
    category: 'classroom',
    jlptLevel: 'N5',
  },
  {
    id: 1021,
    jp: 'テストはいつですか？',
    romaji: 'Tesuto wa itsu desu ka?',
    en: 'When is the test?',
    category: 'classroom',
    jlptLevel: 'N5',
  },
  {
    id: 1022,
    jp: '一緒に勉強しよう。',
    romaji: 'Issho ni benkyou shiyou.',
    en: "Let's study together.",
    category: 'classroom',
    jlptLevel: 'N5',
  },
]

/** Built-in seed when JSON export is unavailable (grammarTags inferred). */
export const SEED_SENTENCES: Sentence[] = RAW_SEED_SENTENCES.map((s) =>
  withGrammarTags(s),
)

export const SEED_VOCAB: VocabEntry[] = [
  {
    id: 1,
    jp: '楽しい',
    romaji: 'tanoshii',
    en: 'fun / enjoyable',
    hiragana: 'たのしい',
    kanji: '楽しい',
    category: 'emotion',
    jlptLevel: 'N5',
    exampleJp: '今日はとても楽しかった！',
    exampleRomaji: 'Kyou wa totemo tanoshikatta!',
    exampleEn: 'Today was really fun!',
  },
  {
    id: 2,
    jp: '嬉しい',
    romaji: 'ureshii',
    en: 'happy',
    hiragana: 'うれしい',
    kanji: '嬉しい',
    category: 'emotion',
    jlptLevel: 'N5',
  },
  {
    id: 3,
    jp: '面白い',
    romaji: 'omoshiroi',
    en: 'interesting',
    hiragana: 'おもしろい',
    kanji: '面白い',
    category: 'emotion',
    jlptLevel: 'N5',
  },
]

export const SEED_PERSONALITY: PersonalityLine[] = [
  {
    id: 1,
    mode: 'calm',
    jp: 'ゆっくり話しましょう。',
    romaji: 'Yukkuri hanashimashou.',
    en: "Let's talk slowly.",
    context: 'greeting',
  },
  {
    id: 2,
    mode: 'supportive',
    jp: '大丈夫だよ。',
    romaji: 'Daijoubu da yo.',
    en: "It's okay.",
    context: 'encouragement',
  },
  {
    id: 3,
    mode: 'playful',
    jp: '面白いね！',
    romaji: 'Omoshiroi ne!',
    en: "That's interesting!",
    context: 'general',
  },
  {
    id: 4,
    mode: 'teacher',
    jp: '一歩ずつ進みましょう。',
    romaji: 'Ippo zutsu susumimashou.',
    en: "Let's take this one step at a time.",
    context: 'encouragement',
  },
]

export const STARTER_SUGGESTIONS: Suggestion[] = [
  {
    jp: 'うん、疲れた',
    romaji: 'Un, tsukareta',
    en: "Yeah, I'm tired",
  },
  {
    jp: '元気だよ',
    romaji: 'Genki da yo',
    en: "I'm doing well",
  },
  {
    jp: '今日は忙しかった',
    romaji: 'Kyou wa isogashikatta',
    en: 'Today was busy',
  },
]
